/**
 * EXERCISE B — Find the weak tests
 *
 * These tests were generated by an AI assistant.
 * They pass, but they don't catch real bugs.
 * Your job: identify what's wrong and write better tests.
 *
 * Hint: run `npm test -- --testPathPattern calculateDiscount` and watch
 * everything go green. Then ask: would you ship this with confidence?
 */

import { calculateDiscount } from '../../src/services/calculateDiscount';

describe('calculateDiscount (weak AI-generated tests)', () => {
  it('returns a result object', () => {
    const result = calculateDiscount({ subtotal: 100, code: 'SAVE10' });
    expect(result).toBeDefined(); // ← WEAK: passes even if discount is wrong
  });

  it('SAVE10 produces a discount', () => {
    const result = calculateDiscount({ subtotal: 100, code: 'SAVE10' });
    expect(result.discountAmount).toBeTruthy(); // ← WEAK: 0 would fail, but 100 passes!
  });

  it('FLAT5 reduces the total', () => {
    const result = calculateDiscount({ subtotal: 50, code: 'FLAT5' });
    expect(result.finalTotal).toBeLessThan(result.discountAmount + result.finalTotal);
    // ← WEAK: this is always true by definition (x < x + y when y > 0)
  });

  it('unknown code does not throw', () => {
    expect(() => calculateDiscount({ subtotal: 100, code: 'NOPE' })).not.toThrow();
    // ← WEAK: only checks it doesn't throw, not what it returns
  });

  it('code is case-insensitive', () => {
    const upper = calculateDiscount({ subtotal: 100, code: 'SAVE10' });
    const lower = calculateDiscount({ subtotal: 100, code: 'save10' });
    // ← WEAK: only checks that discountAmount matches between the two calls,
    //   but never checks what that amount *should be* (10, not 100)
    expect(lower.discountAmount).toBe(upper.discountAmount);
    expect(lower.finalTotal).toBe(upper.finalTotal);
  });

  // Missing tests — can you spot them?
  // 1. What is the exact discountAmount for SAVE10 on $100? (should be $10, not $100)
  // 2. Does FLAT5 apply when the subtotal is below $20? (it shouldn't)
  // 3. Can finalTotal ever go negative? (it shouldn't)
  // 4. What about edge cases: $0 subtotal, very large amounts?
});
